# Generated by Django 2.2.11 on 2020-03-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0033_auto_20200321_1349'),
        ('ihp_people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihpprofile',
            name='request_to_join_group',
            field=models.ManyToManyField(blank=True, to='groups.GroupProfile'),
        ),
    ]
