# Generated by Django 2.2.12 on 2020-04-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihp_people', '0002_ihpprofile_request_to_join_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihpprofile',
            name='approved',
            field=models.BooleanField(blank=True, default=False, help_text='approve user', null=True, verbose_name='Is the user approved?'),
        ),
    ]
