# Generated by Django 2.2.11 on 2020-03-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20171013_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationpage',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='documentationpage',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='partnericon',
            name='upload',
            field=models.FileField(upload_to='partner-ico'),
        ),
    ]
